

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://srv1663.hstgr.io/u242767798_supremenetwork
spring.datasource.username=u242767798_supremenetwork
spring.datasource.password=Supreme@2022#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

security.jwt.expiracao=30
security.jwt.chave-assinatura=YSBsZW1icmUgw6kgYnJhbmNh

spring.main.allow-circular-references=true